{
 "title": "Task Stats",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATA_SOURCE", "label": "Data Source", "query": "grafana-timestream-datasource" },
   {
    "name": "AWS_BATCH_JOB_ID",
    "label": "AWS Batch Job ID",
    "query": "8e418dd6-62bc-4f1a-8d32-e115604c909d"
   },
   {
    "name": "interval",
    "label": "Resolution",
    "query": "10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "HOST",
    "query": "SELECT host\n   FROM \"metricsDB\".\"docker_container_cpu\"\n   WHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\n   LIMIT 1"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT  BIN(time, $interval)                                              AS binned_timestamp\n       ,AWS_BATCH_JOB_ID\n       ,CONCAT('cpu_',measure_name)                                       AS measure\n       ,COALESCE( MIN(measure_value::bigint),MIN(measure_value::double) )/100 AS min\n       ,COALESCE( AVG(measure_value::bigint),AVG(measure_value::double) )/100 AS avg\n       ,COALESCE( MAX(measure_value::bigint),MAX(measure_value::double) )/100 AS max\nFROM \"metricsDB\".\"docker_container_cpu\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID' AND measure_name = 'usage_percent'\nGROUP BY  AWS_BATCH_JOB_ID\n         ,measure_name\n         ,BIN(time, $interval)\nORDER BY binned_timestamp ASC\n",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT  COALESCE( MAX(measure_value::bigint),MAX(measure_value::double) )/100 AS max_measured\n       ,COALESCE( AVG(measure_value::bigint),AVG(measure_value::double) )/100 AS avg_measured\n       --,COALESCE( MIN(measure_value::bigint),MIN(measure_value::double) ) AS min\nFROM \"metricsDB\".\"docker_container_cpu\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID' AND measure_name = 'usage_percent'\nGROUP BY  AWS_BATCH_JOB_ID\n         ,measure_name",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "Accumulated CPU Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT  COALESCE( MAX(measure_value::bigint),MAX(measure_value::double) ) AS usage_total\nFROM \"metricsDB\".\"docker_container_cpu\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID' AND measure_name = 'usage_total'\nGROUP BY  AWS_BATCH_JOB_ID\n         ,measure_name\n",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "Links to Label - Group Stats",
   "type": "table",
   "description": "The metrics labels available for this task, listed from the first CPU entry.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "cpuAssignedCount",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT *\nFROM \"metricsDB\".\"docker_container_cpu\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\nlimit 1",
     "table": "\"aggregated_metrics\""
    }
   ]
  },
  {
   "title": "Accumulated CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 17, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "container_id",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT  BIN(time, $interval)                                              AS binned_timestamp\n       ,AWS_BATCH_JOB_ID\n       ,CONCAT('user_cpu_',measure_name)                                       AS measure\n       ,COALESCE( MAX(measure_value::bigint),MAX(measure_value::double) ) AS user\nFROM \"metricsDB\".\"docker_container_cpu\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID' AND measure_name = 'usage_in_usermode'\nGROUP BY  AWS_BATCH_JOB_ID\n         ,measure_name\n         ,BIN(time, $interval)\nORDER BY binned_timestamp ASC\n",
     "table": "\"docker_container_cpu\""
    },
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT  BIN(time, $interval)                                              AS binned_timestamp\n       ,AWS_BATCH_JOB_ID\n       ,CONCAT('kernel_cpu_',measure_name)                                       AS measure\n       ,COALESCE( MAX(measure_value::bigint),MAX(measure_value::double) ) AS kernel\nFROM \"metricsDB\".\"docker_container_cpu\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID' AND measure_name = 'usage_in_kernelmode'\nGROUP BY  AWS_BATCH_JOB_ID\n         ,measure_name\n         ,BIN(time, $interval)\nORDER BY binned_timestamp ASC\n",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory Used - Amount of memory actively used by the task.\nCache - Size of files cached by the system into unused memory to improve performance.",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "SELECT binned_timestamp\n      ,AWS_BATCH_JOB_ID\n      ,usage_max\n      ,CASE\n          WHEN usage_max + total_cache_max > limit_max THEN limit_max\n          ELSE total_cache_max\n       END AS cache_max\n       ,limit_max\nFROM (\n    SELECT BIN(time, $interval) AS binned_timestamp\n          ,AWS_BATCH_JOB_ID\n          ,MAX(CASE WHEN measure_name = 'usage' THEN measure_value::bigint ELSE NULL END) AS usage_max\n          ,MAX(CASE WHEN measure_name = 'total_cache' THEN measure_value::bigint ELSE NULL END) AS total_cache_max\n          ,MAX(CASE WHEN measure_name = 'limit' THEN measure_value::bigint ELSE NULL END) AS limit_max\n    FROM \"metricsDB\".\"docker_container_mem\"\n    WHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\n      AND measure_name IN ('limit', 'usage', 'total_cache')\n      AND $__timeFilter\n    GROUP BY 1, 2\n) AS grouped_data\nORDER BY binned_timestamp ASC\n",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "bargauge",
   "description": "Limit - memory limit set for the container.\nMax Measured - The maximum amount of memory actively used by the task\nMax Absolute - The maximum memory achieved, including the cache.\nCache - Size of files cached by the system into unused memory to improve performance.\n",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "memory_total",
     "rawQuery": "SELECT \n    AWS_BATCH_JOB_ID,\n    COALESCE(MAX(CASE WHEN measure_name = 'limit' THEN measure_value::bigint END),\n             MAX(CASE WHEN measure_name = 'limit' THEN measure_value::double END)) AS limit,\n    COALESCE(MAX(CASE WHEN measure_name = 'usage' THEN measure_value::bigint END),\n             MAX(CASE WHEN measure_name = 'usage' THEN measure_value::double END)) AS max_measured,\n    COALESCE(AVG(CASE WHEN measure_name = 'usage' THEN measure_value::bigint END),\n             AVG(CASE WHEN measure_name = 'usage' THEN measure_value::double END)) AS avg_measured,\n    COALESCE(MAX(CASE WHEN measure_name = 'max_usage' THEN measure_value::bigint END),\n             MAX(CASE WHEN measure_name = 'max_usage' THEN measure_value::double END)) AS max_absolute,\n     COALESCE(AVG(CASE WHEN measure_name = 'total_cache' THEN measure_value::bigint END),\n             AVG(CASE WHEN measure_name = 'total_cache' THEN measure_value::double END)) AS avg_cache,\n    COALESCE(MAX(CASE WHEN measure_name = 'total_cache' THEN measure_value::bigint END),\n             MAX(CASE WHEN measure_name = 'total_cache' THEN measure_value::double END)) AS max_cache\nFROM \n    \"metricsDB\".\"docker_container_mem\"\nWHERE \n    AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\nGROUP BY \n    AWS_BATCH_JOB_ID\n",
     "table": "\"docker\""
    }
   ]
  },
  {
   "title": "CPU Measurements",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT CONCAT('cpu_', measure_name) as measure_name\n       ,COALESCE( MIN(measure_value::bigint),MIN(measure_value::double) ) AS min\n       ,COALESCE( AVG(measure_value::bigint),AVG(measure_value::double) ) AS avg\n       ,COALESCE( MAX(measure_value::bigint),MAX(measure_value::double) ) AS max\nFROM \"metricsDB\".\"docker_container_cpu\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\nGROUP BY measure_name",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "MEM Measurements",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT CONCAT('mem_', measure_name) as measure_name\n       ,COALESCE( MIN(measure_value::bigint),MIN(measure_value::double) ) AS min\n       ,COALESCE( AVG(measure_value::bigint),AVG(measure_value::double) ) AS avg\n       ,COALESCE( MAX(measure_value::bigint),MAX(measure_value::double) ) AS max\nFROM \"metricsDB\".\"docker_container_mem\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\nGROUP BY measure_name",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "BLKIO Measurements",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT CONCAT('blkio_', measure_name) as measure_name\n       ,MIN(measure_value::bigint) AS min\n       ,AVG(measure_value::bigint) AS avg\n       ,MAX(measure_value::bigint) AS max\nFROM \"metricsDB\".\"docker_container_blkio\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\nGROUP BY measure_name",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "Container Stats Measurements",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT CONCAT('dcs_', measure_name) as measure_name\n       ,MIN(measure_value::bigint) AS min\n       ,AVG(measure_value::bigint) AS avg\n       ,MAX(measure_value::bigint) AS max\nFROM \"metricsDB\".\"docker_container_status\"\nWHERE AWS_BATCH_JOB_ID = '$AWS_BATCH_JOB_ID'\nGROUP BY AWS_BATCH_JOB_ID, measure_name",
     "table": "\"mem\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "options": {
    "content": "<center>\n<h1>Host Monitoring</h1>\n<p>\nThe data below shows metrics of the VM instance <code>$HOST</code>.  \nMultiple tasks can run on one instance.\n</p>\n</center>"
   },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT host, CONCAT('dd_', measure_name) as measure_name\n       ,MIN(measure_value::bigint) AS min\n       ,AVG(measure_value::bigint) AS avg\n       ,MAX(measure_value::bigint) AS max\nFROM \"metricsDB\".\"docker_data\"\nWHERE host = '$HOST'\nGROUP BY host, measure_name",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "Docker Data Measurements",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT CONCAT('dd_', measure_name) as measure_name\n       ,MIN(measure_value::bigint) AS min\n       ,AVG(measure_value::bigint) AS avg\n       ,MAX(measure_value::bigint) AS max\nFROM \"metricsDB\".\"docker_data\"\nWHERE host = '$HOST'\nGROUP BY measure_name",
     "table": "\"mem\""
    }
   ]
  },
  {
   "title": "Device Mapper (dm)",
   "type": "table",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "database": "\"metricsDB\"",
     "measure": "available",
     "rawQuery": "-- Get the overall cpu statistics of a task given the AWS_BATCH_JOB_ID value.\n-- same for mem, just replace cpu by mem IN the lines below.\nSELECT CONCAT('dm_', measure_name) as measure_name\n       ,MIN(measure_value::bigint) AS min\n       ,AVG(measure_value::bigint) AS avg\n       ,MAX(measure_value::bigint) AS max\nFROM \"metricsDB\".\"docker_devicemapper\"\nWHERE host = '$HOST'\nGROUP BY measure_name",
     "table": "\"mem\""
    }
   ]
  }
 ]
}